name: zihun_chats
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5

  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.6

  google_sign_in: ^6.1.4
  lottie: ^2.6.0
  introduction_screen: ^3.1.11
  avatar_glow: ^2.0.2
  emoji_picker_flutter: ^1.6.1
  get_storage: ^2.1.1
  intl: ^0.18.1
  image_picker: ^1.0.2
  flutter: 
    sdk: flutter
  ionicons: ^0.2.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

